version: '3.1'
services:
    nameplate-server:
        build:
          context: ..
          dockerfile: docker/server/Dockerfile
        secrets:
          - nameplate_api_id
          - nameplate_api_passkey

secrets:
  nameplate_api_id:
    file: ./../.keys/nameplate_api_id.txt
  nameplate_api_passkey:
    file: ./../.keys/nameplate_api_passkey.txt
